apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  type: ClusterIP
  selector:
    app-name: db 
  
  ports:
    - port: 8080 # Service port
      targetPort: 80  # Pod/container port
      
    - port: 9000 # Service port
      targetPort: 3000  # Pod/container port
